


# model: directory_name
MODELS = {
    "openai/gpt-4o": "gpt-4o", # https://openrouter.ai/openai/gpt-4o
    "openai/o1-mini": "o1-mini", # https://openrouter.ai/openai/o1-mini
    #"openai/o1-preview": "o1-preview", # https://openrouter.ai/openai/o1-preview
    #"anthropic/claude-3.5-sonnet:beta": "claude-3.5-sonnet", # https://openrouter.ai/anthropic/claude-3.5-sonnet:beta
    #"x-ai/grok-beta": "grok-beta", # https://openrouter.ai/x-ai/grok-beta
    "perplexity/llama-3.1-sonar-large-128k-online": "llama-3.1-sonar-large-128k-online", # https://openrouter.ai/perplexity/llama-3.1-sonar-large-128k-online
    #"meta-llama/llama-3.3-70b-instruct": "llama-3.3-70b-instruct", # https://openrouter.ai/meta-llama/llama-3.3-70b-instruct
    "google/gemini-flash-1.5-8b": "gemini-flash-1.5-8b", # https://openrouter.ai/google/gemini-flash-1.5-8b
    "mistralai/ministral-8b": "ministral-8b", # https://openrouter.ai/mistralai/ministral-8b
    #"cohere/command-r": "command-r", # https://openrouter.ai/cohere/command-r
}

DOW_JONES_INDEX_COMPANIES = [
    {
        "Company": "3M",
        "Exchange": "NYSE",
        "Symbol": "MMM",
        "Industry": "Conglomerate",
        "Added": "1976-08-09",
        "weight": 1.83,
    },
    {
        "Company": "American Express",
        "Exchange": "NYSE",
        "Symbol": "AXP",
        "Industry": "Financial services",
        "Added": "1982-08-30",
        "weight": 4.12,
    },
    {
        "Company": "Amgen",
        "Exchange": "NASDAQ",
        "Symbol": "AMGN",
        "Industry": "Biopharmaceutical",
        "Added": "2020-08-31",
        "weight": 3.76,
    },
    {
        "Company": "Amazon",
        "Exchange": "NASDAQ",
        "Symbol": "AMZN",
        "Industry": "Retailing",
        "Added": "2024-02-26",
        "weight": 3.02,
    },
    {
        "Company": "Apple",
        "Exchange": "NASDAQ",
        "Symbol": "AAPL",
        "Industry": "Information technology",
        "Added": "2015-03-19",
        "weight": 3.33,
    },
    {
        "Company": "Boeing",
        "Exchange": "NYSE",
        "Symbol": "BA",
        "Industry": "Aerospace and defense",
        "Added": "1987-03-12",
        "weight": 2.15,
    },
    {
        "Company": "Caterpillar",
        "Exchange": "NYSE",
        "Symbol": "CAT",
        "Industry": "Construction and mining",
        "Added": "1991-05-06",
        "weight": 5.41,
    },
    {
        "Company": "Chevron",
        "Exchange": "NYSE",
        "Symbol": "CVX",
        "Industry": "Petroleum industry",
        "Added": "2008-02-19",
        "weight": 2.18,
    },
    {
        "Company": "Cisco",
        "Exchange": "NASDAQ",
        "Symbol": "CSCO",
        "Industry": "Information technology",
        "Added": "2009-06-08",
        "weight": 0.82,
    },
    {
        "Company": "Coca-Cola",
        "Exchange": "NYSE",
        "Symbol": "KO",
        "Industry": "Drink industry",
        "Added": "1987-03-12",
        "weight": 0.86,
    },
    {
        "Company": "Disney",
        "Exchange": "NYSE",
        "Symbol": "DIS",
        "Industry": "Broadcasting and entertainment",
        "Added": "1991-05-06",
        "weight": 1.60,
    },
    {
        "Company": "Goldman Sachs",
        "Exchange": "NYSE",
        "Symbol": "GS",
        "Industry": "Financial services",
        "Added": "2013-09-23",
        "weight": 8.18,
    },
    {
        "Company": "Home Depot",
        "Exchange": "NYSE",
        "Symbol": "HD",
        "Industry": "Home Improvement",
        "Added": "1999-11-01",
        "weight": 5.84,
    },
    {
        "Company": "Honeywell",
        "Exchange": "NASDAQ",
        "Symbol": "HON",
        "Industry": "Conglomerate",
        "Added": "2020-08-31",
        "weight": 3.10,
    },
    {
        "Company": "IBM",
        "Exchange": "NYSE",
        "Symbol": "IBM",
        "Industry": "Information technology",
        "Added": "1979-06-29",
        "weight": 3.22,
    },
    {
        "Company": "Johnson & Johnson",
        "Exchange": "NYSE",
        "Symbol": "JNJ",
        "Industry": "Pharmaceutical industry",
        "Added": "1997-03-17",
        "weight": 2.05,
    },
    {
        "Company": "JPMorgan Chase",
        "Exchange": "NYSE",
        "Symbol": "JPM",
        "Industry": "Financial services",
        "Added": "1991-05-06",
        "weight": 3.36,
    },
    {
        "Company": "McDonald's",
        "Exchange": "NYSE",
        "Symbol": "MCD",
        "Industry": "Food industry",
        "Added": "1985-10-30",
        "weight": 4.10,
    },
    {
        "Company": "Merck",
        "Exchange": "NYSE",
        "Symbol": "MRK",
        "Industry": "Pharmaceutical industry",
        "Added": "1979-06-29",
        "weight": 1.42,
    },
    {
        "Company": "Microsoft",
        "Exchange": "NASDAQ",
        "Symbol": "MSFT",
        "Industry": "Information technology",
        "Added": "1999-11-01",
        "weight": 6.06,
    },
    {
        "Company": "Nike",
        "Exchange": "NYSE",
        "Symbol": "NKE",
        "Industry": "Clothing industry",
        "Added": "2013-09-23",
        "weight": 1.08,
    },
    {
        "Company": "Nvidia",
        "Exchange": "NASDAQ",
        "Symbol": "NVDA",
        "Industry": "Information technology",
        "Added": "2024-11-08",
        "weight": 1.99,
    },
    {
        "Company": "Procter & Gamble",
        "Exchange": "NYSE",
        "Symbol": "PG",
        "Industry": "Fast-moving consumer goods",
        "Added": "1932-05-26",
        "weight": 2.41,
    },
    {
        "Company": "Salesforce",
        "Exchange": "NYSE",
        "Symbol": "CRM",
        "Industry": "Information technology",
        "Added": "2020-08-31",
        "weight": 4.95,
    },
    {
        "Company": "Sherwin-Williams",
        "Exchange": "NYSE",
        "Symbol": "SHW",
        "Industry": "Speciality chemicals",
        "Added": "2024-11-08",
        "weight": 5.28,
    },
    {
        "Company": "Travelers",
        "Exchange": "NYSE",
        "Symbol": "TRV",
        "Industry": "Insurance",
        "Added": "2009-06-08",
        "weight": 3.61,
    },
    {
        "Company": "UnitedHealth Group",
        "Exchange": "NYSE",
        "Symbol": "UNH",
        "Industry": "Managed health care",
        "Added": "2012-09-24",
        "weight": 7.93,
    },
    {
        "Company": "Verizon",
        "Exchange": "NYSE",
        "Symbol": "VZ",
        "Industry": "Telecommunications industry",
        "Added": "2004-04-08",
        "weight": 0.58,
    },
    {
        "Company": "Visa",
        "Exchange": "NYSE",
        "Symbol": "V",
        "Industry": "Financial services",
        "Added": "2013-09-23",
        "weight": 4.23,
    },
    {
        "Company": "Walmart",
        "Exchange": "NYSE",
        "Symbol": "WMT",
        "Industry": "Retailing",
        "Added": "1997-03-17",
        "weight": 1.31,
    },
]
